export const defaultPapyrusFeatures = {
    header: true,
    footer: true,
    scrollHeader: true,
    search: true,
    rss: true,
    poweredBy: true,
    themeControls: true,
    share: true,
    toc: true,
    postTags: true,
    aiMetadata: true,
    sourceActions: true,
    postStats: true,
    comments: true,
    postSideLinks: true,
    adjacentPosts: true,
    backToTop: true,
    markdownAlerts: true,
    mermaid: true,
    artifactLinks: true,
    imageZoom: true,
    videoDither: true,
    notes: true,
    projects: true,
    graph: true,
    cv: true,
    linkPreviews: true,
    contentIndex: true,
    sectionMenu: true,
};
export function resolvePapyrusFeatures(features = {}) {
    return {
        ...defaultPapyrusFeatures,
        ...features,
    };
}
